version: '2'
services:
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: monblog
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root

    web:
        build: .
        command: ./entrypoint.sh
        volumes:
        - .:/code
        ports:
        - "8001:8001"
        depends_on:
        - db
